Models/ErrorViewModel.cs
namespace MVCRehberUyg.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Kisiler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;

namespace MVCRehberUyg.Models
{
    public class Kisiler
    {
        [Key]
        public int? KisiNo {get; set;}
        public string? Ad {get; set;}
        public string? Soyad {get; set;}
        public long? TelefonNo {get; set;}
        public string? Resim {get; set;}
        // bos bırakılabilir bir alan olması için ? ekledik.
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCRehberUyg.Models;

namespace MVCRehberUyg.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RehberYonetimController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCRehberUyg.Data;
using MVCRehberUyg.Models;

namespace MVCRehberUyg.Controllers
{
    //[Route("[controller]")]
    public class RehberYonetimController : Controller
    {
        private readonly ILogger<RehberYonetimController> _logger;
        private readonly SanalVeritabani _context;

    

        public RehberYonetimController(ILogger<RehberYonetimController> logger,SanalVeritabani context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() // kişileri listeleme indexi ,home daki ındex sayfa indexi
        {
            return View(model:_context.Kisilers);
        }

        [HttpGet]
        public IActionResult Ekle() // ekleme formuna yönlendirecek 
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Kisiler yeniKisi) // formdan gelen kişiyi ekleyecek
        {
            _context.Kisilers.Add(yeniKisi);
            return RedirectToAction("Index");
        }

        public IActionResult Detaylar(int id)
        {
            // hangi id hangi personelin?
            var kisiler = _context.Kisilers.SingleOrDefault(k => k.KisiNo ==id);
            return View(model:kisiler);
        }
        [HttpGet]
        public IActionResult Duzenle(int id) // formu açıyor 
        {
            var kisiler = _context.Kisilers.SingleOrDefault(k => k.KisiNo ==id);
            return View(model:kisiler);
        }
        [HttpPost]
        public IActionResult Duzenle(Kisiler duzenlenmisKisiler) // formdan gelen veriyi açıyor.
        {
            var kisiler = _context.Kisilers.SingleOrDefault(k => k.KisiNo == duzenlenmisKisiler.KisiNo);
            kisiler.Ad= duzenlenmisKisiler.Ad;
            kisiler.Soyad=duzenlenmisKisiler.Soyad;
            kisiler.TelefonNo=duzenlenmisKisiler.TelefonNo;
            return RedirectToAction("Index");
        }
        
        
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}

<div class="text-center">
    <h1 class="display-5">Telefon Rehberine Hoşgeldiniz</h1>
    <p>İşlemler için soldaki menüyü kullanabilirsiniz.</p>
</div>

Views/RehberYonetim/Detaylar.cshtml
@model Kisiler
@{
    ViewData["Title"] = "Kisi Detayları";
}

<h1>Kişi Detayları</h1>
<div class="card" style="width: 18rem;">
  <img src="~/resimler/gorseller/@Model.Resim" class="card-img-top" alt="Kişi Resmi">
  <div class="card-body">
    <h5 class="card-title">@Model.Ad @Model.Soyad</h5>
    <p class="card-text">
        <strong>Kişi No:</strong> @Model.KisiNo
    </p>

    <p class="card-text">
        <strong>Telefon Numarası:</strong> @Model.TelefonNo
    </p>
    
    <a asp-controller="RehberYonetimi" asp-action="Index" class="btn btn-primary">Listeye Geri Dön</a>
  </div>
</div>

Views/RehberYonetim/Duzenle.cshtml
@model Kisiler
@{
    ViewData["Title"] = "Düzenleme Sayfası";
}

<hı>Kişi Güncelleme Formu</h>

<form asp-action="Duzenle" method="post">
    <p>
        <label for="KisiNo">KisiNo</label>
        <input type="number" asp-for="KisiNo" id="Kisino" class="form-control">
    </p>

     <p>
        <label for="Ad">Ad</label>
        <input type="text" asp-for="Ad" id="Ad" class="form-control">
    </p>

     <p>
        <label for="Soyad">Soyad</label>
        <input type="text" asp-for="Soyad" id="Soyad" class="form-control">
    </p>

     <p>
        <label for="TelefonNo">TelefonNo</label>
        <input type="number" asp-for="TelefonNo" id="TelefonNo" class="form-control">
    </p>

     <p>
        <label for="Resim">Resim</label>
        <input type="text" asp-for="Soyad" id="Soyad" class="form-control">
    </p>

    <p>
        <input type="submit" value="Kaydet" class="btn btn-primary">
    </p>


</form>

Views/RehberYonetim/Ekle.cshtml
@model Kisiler
@{
    ViewData["Title"] = "Ekleme Sayfası";
}

<hı>Kişi Ekleme Formu</h>

<form asp-action="Ekle" method="post">
    <p>
        <label for="KisiNo">KisiNo</label>
        <input type="number" asp-for="KisiNo" id="Kisino" class="form-control">
    </p>

     <p>
        <label for="Ad">Ad</label>
        <input type="text" asp-for="Ad" id="Ad" class="form-control">
    </p>

     <p>
        <label for="Soyad">Soyad</label>
        <input type="text" asp-for="Soyad" id="Soyad" class="form-control">
    </p>

     <p>
        <label for="TelefonNo">TelefonNo</label>
        <input type="number" asp-for="TelefonNo" id="TelefonNo" class="form-control">
    </p>

     <p>
        <label for="Resim">Resim</label>
        <input type="text" asp-for="Soyad" id="Soyad" class="form-control">
    </p>

    <p>
        <input type="submit" value="Kaydet" class="btn btn-primary">
    </p>


</form>

Views/RehberYonetim/Index.cshtml
@model List<Kisiler>
@{
    ViewData["Title"] = "Kişiler Listesi";
}


<h1>Kisiler Listesi</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>KisiNo</th>
            <th>Ad</th>
            <th>Soyad</th>
            <th>TelefonNo</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.KisiNo</td>
                <td>@item.Ad</td>
                <td>@item.Soyad</td>
                <td>@item.TelefonNo</td>
                <td>
                    <a asp-controller="RehberYonetimi" asp-action="Detaylar" asp-route-id="@item.KisiNo"
                        class="btn btn-info"><i class="bi bi-info-circle"></i>Detaylar</a>
                    <a asp-controller="RehberYonetimi" asp-action="Duzenle" asp-route-id="=@item.KisiNo"
                        class="btn btn-warning"><i class="bi bi-pencil-square"></i>Düzenle </a>
                    <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"><i
                            class="bi bi-trash3"></i>Sil</a>
                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
                        tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    ...
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary">Understood</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCRehberUyg</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCRehberUyg.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCRehberUyg</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCRehberUyg - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Sablon.cshtml
<!doctype html>
<html lang="tr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@ViewData["Title"] Telefon Rehberi</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="~/css/styles.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-navbar">
    <div class="container">
      <a class="navbar-brand" asp-controller="Home" asp-action="Index">Admin Panel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Giriş</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="bi bi-envelope-check"></i> İletişim</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i> Yönetici
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#"><i class="bi bi-person-lines-fill"></i> Profil</a></li>
              <li><a class="dropdown-item" href="#"><i class="bi bi-key-fill"></i> Şifre Değiştir</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Çıkış <i class="bi bi-box-arrow-right"></i></a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container bg-light">
    <div class="row">
        <img class="img-fluid p-0" src="~/resimler/BACKGROUND.png" alt="Telefon Rehberi">
    </div>

    <div class="row py-3">      
      <div class="col-md-3">
        <div class="list-group">
          <a href="#" class="list-group-item disabled">
            <h5>Rehber İşlemleri</h5>
          </a>
          <a class="list-group-item" asp-controller="RehberYonetim"asp-action="Index"><i class="bi bi-people-fill"></i> Kişiler Listesi</a>
          <a class="list-group-item" asp-controller="RehberYonetim" asp-action="Ekle"><i class="bi bi-person-fill-add"></i> Yeni Kişi Ekle</a>
        </div>
      </div>

      <div class="col-md-9">
        @RenderBody()
      </div>
    </div>

    
  </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>